env:
  browser: true
  commonjs: true
  es2021: true
  jest/globals: true
extends:
  - eslint:recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
  - 'jest'
rules: {
  "semi" : ["error", "always"],
  "quotes" : ["error", "double"]
}
