version: "3.9" # optional since v1.27.0
services:
  testo:
      image: dykoffi/testo:latest
      container_name: testo
      environment:
        - DATABASE_URL=postgres://testo_user:3080@testo_db_staging/testo_db_staging
      depends_on:
        - testo_db_staging
      ports:
        - 38863:8080

  testo_db_dev:
    image: postgres:14-alpine
    container_name: testo_db_dev
    environment:
      - POSTGRES_USER=testo_user
      - POSTGRES_DB=testo_db_dev
      - POSTGRES_PASSWORD=3080
    ports:
      - 34705:5432
    volumes:
      - testo_vol_dev:/var/lib/postgresql/data

  testo_db_staging:
    image: postgres:14-alpine
    container_name: testo_db_staging
    environment:
      - POSTGRES_USER=testo_user
      - POSTGRES_DB=testo_db_staging
      - POSTGRES_PASSWORD=3080
    ports:
      - 42741:5432
    volumes:
      - testo_vol_staging:/var/lib/postgresql/data

  testo_prometheus:
      image: prom/prometheus
      container_name: testo_prometheus
      ports:
        - 9090:9090
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # depends_on:
      #   - testo


volumes:
  testo_vol_dev:
    driver: local
  testo_vol_staging:
    driver: local
